#pragma once

#define IDD_B5CACHEVISUALIZER_DIALOG 102
#define IDC_EDIT_TRACE 1000
#define IDC_BUTTON_RUN 1001
#define IDC_BUTTON_RESET 1002
#define IDC_EDIT_RESULT 1003
#define IDC_STATIC_SUMMARY 1004

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 103
#define _APS_NEXT_COMMAND_VALUE 32771
#define _APS_NEXT_CONTROL_VALUE 1005
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
